#!/bin/bash
#given a file it prints the string form gfid
# Example:
#root - /home/pranithk/workspace/gerrit-repo (xattr-retrieval)
#16:15:59 :) ⚡ gfidstr /home/gfs/r2_0/1
#getfattr: Removing leading '/' from absolute path names
#0697aa63-3668-41da-ae05-1e79820f1843
#
g=$(getfattr -n trusted.gfid -e hex $1 | grep trusted.gfid | cut -f2 -d'x')
echo ${g:0:8}-${g:8:4}-${g:12:4}-${g:16:4}-${g:20:16}
