#!/bin/bash
url=$1
wget $url -O out
for file in $(grep tar.xz out | sed -E 's/.*href="([^"]*).*/\1/g')
do
        echo "$url/$file"
        wget $url/$file
        xz -d $file
        tar xvf ${file%%.xz}
        rm -f   ${file%%.xz}
done
